### ISSUE TITLE
Missing tag v1.25.0

### ISSUE THREAD

**Issue by P4sca1** [galexrt/container-healthchecks#58]
The tag v1.25.0 is missing from Quai.io and Docker Hub.

**Comment by galexrt** [comment]
The image tags that are being published have the date added to them, e.g., see https://github.com/galexrt/container-healthchecks/tags and https://quay.io/repository/galexrt/healthchecks?tab=tags&tag=latest

The v1.25.0 is missing right now, I'll look into why that moving tag isn't created anymore.

Docker Hub is not updated anymore, see https://github.com/galexrt/container-healthchecks#container-healthchecks "Container Image available from" list.

**Comment by galexrt** [comment]
I have resolved the issue, v1.25.0 is now available on ghcr.io and quay.io
