### ISSUE TITLE
Container healthcheck not working

### ISSUE THREAD

**Issue by P4sca1** [galexrt/container-healthchecks#59]
The container exits every few seconds / minutes. The log shows the following:
```
2022-03-05 02:02:10,796 INFO stopped: pruneflips (terminated by SIGTERM)
2022/03/05 02:02:10 [notice] 17#17: signal 15 (SIGTERM) received from 1, exiting
2022/03/05 02:02:10 [notice] 24#24: exiting
2022/03/05 02:02:10 [notice] 24#24: exit
2022/03/05 02:02:10 [notice] 17#17: signal 17 (SIGCHLD) received from 24
2022/03/05 02:02:10 [notice] 17#17: worker process 24 exited with code 0
2022/03/05 02:02:10 [notice] 17#17: exit
2022-03-05 02:02:10,806 INFO stopped: nginx (exit status 0)
[2022-03-05 02:02:10 +0000] [16] [INFO] Handling signal: term
[2022-03-05 02:02:10 +0000] [28] [INFO] Worker exiting (pid: 28)
[2022-03-05 02:02:11 +0000] [16] [INFO] Shutting down: Master
2022-03-05 02:02:11,155 INFO stopped: gunicorn (exit status 0)
exited with code 0
```

I am using the tag v1.25.0

**Comment by P4sca1** [comment]
I found out that the reason for this is, that the `HEALTHCHECK`, which is defined in the `Dockerfile` does not work.
I have configured my host to automatically restart containers when they get unhealthy.

**Comment by P4sca1** [comment]
You can verify this using `docker ps`. The healthchecks container always stays at `(health: starting)`.

**Comment by galexrt** [comment]
@P4sca1 I'm unable to reproduce the issue with the container being unhealthy.

```
f1eee63e1072   ghcr.io/galexrt/healthchecks:main   "/entrypoint.sh app:…"   48 seconds ago   Up 47 seconds (healthy)   2525/tcp, 0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   container-healthchecks-hc-1
```

Could you please try increasing the `--tries=` flag for the `HEALTHCHECK` `wget` command in a custom built version of the image?

**Comment by P4sca1** [comment]
I tried running the healthcheck command manually inside the container and this is the output:
```
healthchecks@78819edc6725:/data$ wget --tries=1 --spider http://localhost:8000 || echo "failed"
Spider mode enabled. Check if remote file exists.
--2022-03-09 12:02:41--  http://localhost:8000/
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:8000... connected.
HTTP request sent, awaiting response... 400 Bad Request
Remote file does not exist -- broken link!!!

failed
```

**Comment by swoga** [comment]
Does the Web UI work?
Can you show us your docker-compose.yml?

> 400 Bad Request

This looks like a problem with `healtchecks` itself.

**Comment by P4sca1** [comment]
Yes, the WebUI works. I am running it behind a Nginx proxy. Here's my `docker-compose.yml`:

```
healthchecks:
    image: ghcr.io/galexrt/healthchecks:v1.25.0
    restart: unless-stopped
    environment:
      ALLOWED_HOSTS: hc.my-domain.com
      DB: mysql
      DB_HOST: ***
      DB_NAME: ***
      DB_PASSWORD: ***
      DB_PORT: 3306
      DB_USER: ***
      DEBUG: "False"
      DEFAULT_FROM_EMAIL: hc@my-domain.com
      DISCORD_CLIENT_ID: ***
      DISCORD_CLIENT_SECRET: ***
      EMAIL_HOST: ***
      EMAIL_HOST_PASSWORD: ***
      EMAIL_HOST_USER: ***
      EMAIL_PORT: 587
      SECRET_KEY: ***
      SITE_NAME: Healthchecks | My Name
      SITE_ROOT: https://my-domain.com
    ports:
       - 8000:8000/tcp
```

**Comment by P4sca1** [comment]
Removing `ALLOWED_HOSTS` fixes the issue. I am currently trying to find out, what needs to be added to the list in order to allow connections from inside the container.

**Comment by swoga** [comment]
`ALLOWED_HOSTS` must include `localhost`, see: https://github.com/galexrt/container-healthchecks#environment-configuration-variables

**Comment by P4sca1** [comment]
Thank you, I missed that one in the README. After adding `localhost` to `ALLOWED_HOSTS`, the healthcheck is working.
